const apiConstants = {
    GET_PRODUCT_LISTS: "GET_PRODUCT_LISTS",
    GET_PRODUCT_LISTS_SUCCESS: "GET_PRODUCT_LISTS_SUCCESS",
    GET_PRODUCT_LISTS_FAIL: "GET_PRODUCT_LISTS_FAIL",

    UPDATE_PRODUCT_LISTS: "UPDATE_PRODUCT_LISTS",
    UPDATE_PRODUCT_LISTS_SUCCESS: "UPDATE_PRODUCT_LISTS_SUCCESS",
    UPDATE_PRODUCT_LISTS_FAIL: "UPDATE_PRODUCT_LISTS_FAIL",

};
export default apiConstants;
